name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what went wrong
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should have happened
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: What version of the Local Recommendations plugin are you running?
      placeholder: "e.g., 0.1.0"
    validations:
      required: true

  - type: input
    id: jellyfin-version
    attributes:
      label: Jellyfin Version
      description: What version of Jellyfin are you running?
      placeholder: "e.g., 10.11.5"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS is your Jellyfin server running on?
      placeholder: "e.g., Ubuntu 22.04, Windows Server 2022, Docker"
    validations:
      required: true

  - type: input
    id: dotnet
    attributes:
      label: .NET Runtime Version
      description: What .NET runtime version is installed?
      placeholder: "e.g., 9.0.0"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output. This will be automatically formatted.
      placeholder: |
        Paste log excerpts here (please sanitize any personal information like usernames, IP addresses, file paths)
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have sanitized all personal information from logs and descriptions
          required: true
        - label: I am using a supported version of Jellyfin (10.11.5+)
          required: true
